---
- hosts: development
  become: yes
  roles:
    - vim-install
    - yum-update
    - xfce-install
    - php7-install
    - docker-install
    - ansible-container-install

- hosts: development
  roles:
    - vim-yml
    - vim-configure
    - get-disk-space

